### ISSUE TITLE
the elevation offsets aren't correct---red rocks

### ISSUE THREAD

**Issue by salutonalpha** [connormanning/entwine-cesium-pages#5]
I tested the red rocks data, but the output is above the earth's surface, how should I to fix this issue?

**Comment by connormanning** [comment]
Try switching the `Terrain` to the "STK World Terrain Meshes" which models the actual surface of the earth, rather than the ellipsoid model.  Over the WGS84 ellipsoid this dataset is indeed far above the earth.

**Comment by salutonalpha** [comment]
Thank you for reply

Could you tell me how to set the value of elevation when I using entwine-cesium-pages to produce .pnts files? Because I use the Bing maps as the tileset for earth surface.
![default](https://cloud.githubusercontent.com/assets/28304505/25662306/a9923caa-3046-11e7-8bad-a43de6813056.PNG)

**Comment by connormanning** [comment]
I think I'm confused about what you are trying to do.  If you display this dataset against the WGS84 ellipsoid, it does indeed float.  This is because the elevation of this dataset is high above the model ellipsoid.  The data is not "above the earth's surface", but it is above the WGS84 ellipsoid which does not accurately model the earth's surface at a given local area - especially at a high-altitude region like this one.  Take a look [here](http://cesium.entwine.io/?resource=red-rocks) and you can see that it fits properly against the actual terrain meshes - then switch to WGS84 terrain and see the difference. 

If you want the elevation of the data lowered to be closer to the WGS84 ellipsoid you would have to transform the data beforehand (or manually edit the tileset transform to lower it).  Although it seems to me that you might want to just use the terrain meshes as your terrain provider with your Bing maps imagery provider, in which case it will match up just fine.

**Comment by connormanning** [comment]
The same is true for any dataset, by the way.  Take a look at St. Helens and Autzen on cesium.entwine.io and switch between terrain providers to see the difference between the ellipsoid model and the actual terrain of the earth's surface.

**Comment by connormanning** [comment]
There was some discussion on this here: https://github.com/connormanning/entwine/issues/28

**Comment by salutonalpha** [comment]
Thank you very much, it works.

I suddenly realized that I could load terrain meshes and Bing maps at the same time.
