### ISSUE TITLE
Problem importing a laz file

### ISSUE THREAD

**Issue by jey3dee** [connormanning/entwine-cesium-pages#9]
Hi,

I would appreciate some help regarding the following issue. I'm trying to import a .laz file i created from a .txt file via pdal. The following command is used:

```
docker run -it \
    -v $HOME:$HOME \
    connormanning/entwine \
    build /var/entwine/config/cesium.json \
        -i ~/Downloads/data/00001.laz \
        -o ~/Downloads/data/entwine-cesium-pages/data/demo
```

This results into the following error:

```
Performing dataset inference...
1 / 1: /home/user/Downloads/data/00001.laz
Exception in pool task: No default SRS supplied, and none inferred
Encountered an error: filters.transformation: Too few entries in transformation matrix: 0 (should be 16)
Exiting.
```

The .laz file is created using this command:

`sudo docker run -v /path/to/directory:/data pdal/pdal:1.5 pdal translate /data/00001.txt /data/00001.laz`

This are the first few lines from the .txt file:

```
X,Y,Z
4105953.44416483,824077.998417016,4105953.44416483
4105954.95843044,824077.240487481,4105954.95843044
4105957.66351346,824075.817277363,4105957.66351346
```

Does this happen because the created .laz file is somehow broken?

**Comment by connormanning** [comment]
It looks like the issue is from this portion: `No default SRS supplied, and none inferred`.  Cesium indexing requires reprojection, and your file doesn't seem to have an SRS - so entwine doesn't know where your data is positioned globally.  You'll either need to supply an SRS to entwine with `-r <your SRS here> EPSG:4978` or set the SRS with the `writers.las.a_srs` option during your `pdal translate` step.

**Comment by jey3dee** [comment]
Thank you for your quick reply. Actually I have no idea what an SRS describes. I specified the points in WGS 84, no offset of any kind. What would the SRS be in this case?

**Comment by jey3dee** [comment]
Sorry, I mean ECEF, not WGS 84.

**Comment by connormanning** [comment]
That should be `EPSG:4978`, so you would need `-r EPSG:4978 EPSG:4978`, which is a bit odd but should work.  Your file excerpt looks a bit strange - the X values are exactly equal to the Z values?  Is this synthetic data for testing purposes?  If you could share a link to the file (or email it to me) it would be helpful since I could test it myself.

**Comment by jey3dee** [comment]
Ok, thank you very much. I will try that. Maybe I'll come back to your offer.

You're right, X seems to equal Z. The data is not synthetical, so that may indicate a bug in my export algorithm. The file was converted from a .pcd file.

**Comment by connormanning** [comment]
I would try without Cesium first to verify that your file looks right without reprojection.

```
docker run -it -v $HOME:$HOME connormanning/entwine build \
    -i ~/Downloads/data/00001.laz -o ~/Downloads/data/00001

docker run -it -v $HOME:$HOME -p 8080:8080 connormanning/greyhound -p ~/Downloads/data
```

Then look at http://potree.entwine.io/data/custom.html?s=localhost:8080&r=00001 and make sure things look as you'd expect.

**Comment by jey3dee** [comment]
I got it working. Thank you very much again for your help :). If somebody is interested how I imported points from a .txt file, this are my commands:

```
sudo docker run -v ~/data:/data pdal/pdal:1.5 pdal translate /data/input/dataset.txt /data/output/dataset.las
docker run -it \
    -v $HOME:$HOME \
    connormanning/entwine \
    build /var/entwine/config/cesium.json \
	-r EPSG:4978 EPSG:4978 \
        -i ~/data/dataset.las \
        -o ~/Downloads/entwine-cesium-pages/data/demo
chown -R geo:geo ~/Downloads/entwine-cesium-pages/data/demo
```

The .txt-file itself has the header:
`X,Y,Z,Red,Green,Blue`
Colors are 8 bit per channel (0-255).
